version: '3.7'

services:
  ocds-publisher:
    container_name: 'ocds-publisher'
    build: .
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    expose:
      - ${SERVICE_PORT}
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
